version: "3.8"

services:
  app:
    build: .
    ports:
      - "7007:8080"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: foodsystem
    ports:
      - "5432:5432"
